### ISSUE TITLE
Source code generation of Power A Plus Plane 3D equation incorrect variable names

### ISSUE THREAD

**Issue by aulichny3** [equations-project/pyeq3#3]
**Describe the bug**
The code generator on the http://findcurves.com website for all languages wrt the Power A Plus Plane 3D equation references the variables ```x``` and ```y``` when the input variables are ```x_in``` and ```y_in```
The rendered line in question for the python example is
```
temp = temp + (d * x) + (f * y) + g
```
**To Reproduce**
Below is the auto generated code for python. 
```
# To the best of my knowledge this code is correct.
# If you find any errors or problems please contact
# me directly using zunzun@zunzun.com.
#
#      James


import math

# Fitting target: lowest sum of squared absolute error
# Fitting target value = 0.012737577462104415

def Power_PowerA_PlusPlane_model(x_in, y_in):
    temp = 0.0

    # coefficients
    a = -6.5352240920667448E-01
    b = -7.8288773719368987E-01
    c = 1.3832640065415780E+00
    d = 8.3529192808577880E-05
    f = 1.2984678799990919E+00
    g = -7.8447967544527167E-02

    temp = a * (math.pow(x_in, b) + math.pow(y_in, c))
    temp = temp + (d * x) + (f * y) + g
    return temp
```
Output will yield:
```
NameError                                 Traceback (most recent call last)
Cell In [57], line 1
----> 1 powerA_plus_Plane3D(125, 1.6)

Cell In [55], line 126, in powerA_plus_Plane3D(x_in, y_in)
    123 g = -7.8447967544527167E-02
    125 temp = a * (math.pow(x_in, b) + math.pow(y_in, c))
--> 126 temp = temp + (d * x) + (f * y) + g
    127 return temp

NameError: name 'x' is not defined
```

**Expected behavior**
f(125,1.6) ~ 0.742604055260553

**Desktop (please complete the following information):**
This output is from the website implementation at http://findcurves.com
My understanding is that the codebase has been relocated from bitbucket to this repo.

**Comment by bobmyhill** [comment]
Thanks for the full description, @aulichny3 .

I've fixed the bug in #4, so the main branch should now be correct. I'll make a new release on pypi soon.

I am not the owner of findcurves.com - it might be worth raising the update with Ross so that he can update the website: https://groups.google.com/g/findcurves
